spring.application.name=epicontrol


# Desabilita o cache do Thymeleaf para ver as alterações em HTML imediatamente
spring.thymeleaf.cache=false

# Firebase Configuration
firebase.api.key=AIzaSyBBxF_XNUkyMwfLo1OWgrqGpgqGj6cfj8A
firebase.auth.url=https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword