spring.application.name=epicontrol

# Desabilita o cache do Thymeleaf para ver as alterações em HTML imediatamente
spring.thymeleaf.cache=false

# URL do seu endpoint de autenticação no backend Node.js
api.auth.url=http://localhost:8081/api/auth/login

# URL do endpoint de colaboradores
api.colaborador.url=http://localhost:8081/api/colaboradores

# URL do endpoint de EPIs
api.epi.url=http://localhost:8081/api/epis
